### ISSUE TITLE
Peer-to-Peer

### ISSUE THREAD

**Issue by VanessaAoki** [anapdh/tictactoe-ruby#3]

**Comment by VanessaAoki** [comment]
`
def did_win? symbol = !turn ? @@player1.symbol : @@player2.symbol (0..2).each do |i| return true if board[0 + (3 * i)] == symbol && board[1 + (3 * i)] == symbol && board[2 + (3 * i)] == symbol return true if board[0 + i] == symbol && board[3 + i] == symbol && board[6 + i] == symbol end return true if board[0] == symbol && board[4] == symbol && board[8] == symbol return true if board[2] == symbol && board[4] == symbol && board[6] == symbol false end `

**Comment by elberthcorniell** [comment]
Some methods defined can be in a Game or TicTacToe class cause they can be reused.

**Comment by anapdh** [comment]
issues solved. Thanks.
